# Generated by Django 5.1.5 on 2025-02-03 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='password',
        ),
    ]
