# Generated by Django 5.1.5 on 2025-02-04 17:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_remove_developer_login_alter_developer_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='id',
            field=models.CharField(default=uuid.UUID('0adda541-8f05-43b6-897c-78b4dd238df1'), editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
