# Generated by Django 5.1.5 on 2025-02-04 17:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0004_alter_developer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fe2e8bf7-f12a-4794-8aa4-5393e50d7e37'), editable=False, primary_key=True, serialize=False),
        ),
    ]
